name: 'Generate ArgoCD Application'
description: 'Generates an ArgoCD application YAML file'
inputs:
  appName:
    description: 'Application name'
    required: true
  repoUrl:
    description: 'Repository URL'
    required: true
  manifestsPath:
    description: 'Path to Kubernetes manifests in the repository'
    required: true
  namespace:
    description: 'Destination namespace'
    required: true
  syncPolicy:
    description: 'Sync policy'
    required: false
    default: 'automated'
  templatePath:
    description: 'Path to save the generated YAML file'
    required: false
    default: '.'
  env:
    description: 'Environment Name'
    required: false
    default: ''
  envPrefix:
    description: 'Add environment prefix to add to the application name'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Generate ArgoCD Application
      run: |
        template='
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: ${{ env.envPrefix == 'true' && (inputs.env + '-') || '' }}${{ inputs.appName }}
          namespace: argocd
          finalizers:
          - resources-finalizer.argocd.argoproj.io
        spec:
          project: default
          source:
            repoURL: {{ .Values.spec.source.repoURL }}
            targetRevision: {{ .Values.spec.source.targetRevision }}
            path: ${{ inputs.manifestsPath }}
          destination:
            server: {{ .Values.spec.destination.server }}
            namespace: ${{ inputs.namespace }}
          syncPolicy:
            automated: {}
        '
        echo "${template}" > ${{ inputs.templatePath }}/${{ inputs.appName }}.yaml
      shell: bash